# Tell Travis you want a Python environment to test in
language: python
# List the versions of Python you'd like to test against
python:
 - "2.6"
 - "2.7"
 - "3.2"
 - "3.3"
 - "3.4"
# List the versions of Django you'd like to test against
env:
 - DJANGO_VERSION=1.3.7
 - DJANGO_VERSION=1.4.10
 - DJANGO_VERSION=1.5.4
 - DJANGO_VERSION=1.6.5
matrix:
  exclude:
    - python: "3.2"
      env: "DJANGO_VERSION=1.4.10"
    - python: "3.2"
      env: "DJANGO_VERSION=1.3.7"
    - python: "3.2"
      env: "DJANGO_VERSION=1.2.7"
    - python: "3.3"
      env: "DJANGO_VERSION=1.4.10"
    - python: "3.3"
      env: "DJANGO_VERSION=1.3.7"
    - python: "3.4"
      env: "DJANGO_VERSION=1.4.10"
    - python: "3.4"
      env: "DJANGO_VERSION=1.3.7"
# Tell it the things it will need to install when it boots
install: 
   # Install whatever version of Django that's listed above
   # Travis is currently working on
 - pip install -q Django==$DJANGO_VERSION
 - pip install pyflakes pep8 coverage python-coveralls
 - python setup.py install
# Tell Travis how to run the test script itself
script:
 - pep8 softhyphen
 - pyflakes softhyphen
 - coverage run setup.py test
# Report coverage results to coveralls.io
after_success:
 - coveralls
